# Numpy

In [ ]:
# pip install numpy

In [ ]:
import numpy
numpy.__version__

## Array creation 

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.dtype)
print(a.shape)

In [ ]:
print(a)
print(a[1])
a[0] = 6
print(a)

In [ ]:
a = np.array([[1,2,3,4,5]]) # double square brackets = 2 dimension
print(a)
print(a.shape)

In [ ]:
a = np.array([[1],[2],[3],[4],[5]]) # number of elements = number of rows, number of elements inside sub-list = columns
print(a)
print(a.shape)

In [ ]:
list1 = [[1,2,3,4],[5,6,7,8]]
a = np.array(list1)
print(a)
print(a.shape)

In [ ]:
print(a)
print(a[0,1])
a[0,2] = 9
a[1,0] = 10
print(a)

In [ ]:
list1 = [1,2,3,4,5]               # single dimensional
list2 = [[1,2,3,4],[5,6,7,8]]     # two dimensional

a = np.array(list1)
b = np.array(list2)
print(a)
print(a.shape)
print(b)
print(b.shape)

## Array functions

### Reshape

In [ ]:
list1 = [1,2,3,4,5,6,7,8,9,10]
a = np.array(list1)
print(a)

print(a.reshape(2,5))
print(a.reshape(5,-1))
print(a.reshape(-1,1))

### Ravel

In [ ]:
list1 = [1,2,3,4,5,6,7,8,9,10]
a = np.array(list1)
print(a)

b = a.reshape(2,5)
print(b)
c = b.ravel() # convert into single dimension
print(c)
print(c.shape)

### Tolist

In [ ]:
list1 = [1,2,3,4,5,6,7,8,9,10]
a = np.array(list1)
print(a)
b = a.tolist()
print(b)

### Data type conversion

In [ ]:
import numpy as np

x = np.array([1,2])
print(x)
print(x.dtype)

y = np.array([1.,2.]) # even 1 float number is sufficient to make it a float array
print(y)
print(y.dtype)

z = np.array([1,2], dtype = float)
print(z)
print(z.dtype)

a = np.array([1.2,2.5], dtype = int)
print(a)
print(a.dtype)

### Frequently used arrays

In [ ]:
a = np.zeros((2,2))
print(a)
b = np.zeros((2,2), dtype = int)
print(b)

In [ ]:
a = np.ones((2,3))
print(a)
b = np.ones((2,3), dtype = int)
print(b)

In [ ]:
a = np.full((2,3),4)
print(a)
b = np.full((2,3),4, dtype = float)
print(b)

In [ ]:
a = np.eye(4, dtype = int)
print(a)

In [ ]:
a = np.random.random((4,4))
print(a)

In [ ]:
a = np.random.randint(1,100,(3,3))
print(a)

## Array Slicing

In [ ]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

print(a[0:2,1:3])

In [ ]:
print(a)
print(a[:-2,:-1])

In [ ]:
print(a)
print(a[::2,1::2])
print(a[:-1,::3])

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b = a[::2,1::2]
print(b)
b[0,0] = 99
print(b)
print(a)

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[1:3,1:3])
print(a[1:3,[0,1,3]]) # selective indexing

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b = a>5
print(b)
c=a[b]    # boolean indexing
print(c)

## Array Operations

In [ ]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)
print(a+b) # elementwise addition
print(np.add(a,b))

In [ ]:
print(a)
print(b)
print(a-b) # elementwise subtraction
print(np.subtract(a,b))

In [ ]:
print(a)
print(b)
print(a*b) # elementwise multiplication
print(np.multiply(a,b))

In [ ]:
print(a)
print(b)
print(a/b) # elementwise division
print(np.divide(a,b))

In [ ]:
print(a)
b = np.sqrt(a)
print(b)

In [2]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)
x = np.array([9,10])
y = np.array([11,12])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[ 9 10]
[11 12]


In [ ]:
print(x.dot(y))
print(np.dot(x,y))

In [ ]:
print(a.dot(x))
print(np.dot(a,x))

In [ ]:
print(a.dot(b)) # for 2dim, columns of a == rows of b , result = rows of a and ccolumns of b
print(np.dot(a,b))

In [3]:
print(a)
print(a.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [9]:
import numpy as np
a = np.array([[1,2],[3,4]])
print(a)
print(a.sum())
print(np.sum(a))
print(np.sum(a, axis = 0))
print(np.sum(a, axis = 1))

[[1 2]
 [3 4]]
10
10
[4 6]
[3 7]


In [12]:
print(np.arange(1,10,0.5))

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
